<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>boston_timing_system</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\logo-boston-cut-new.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.3" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Helpers\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\*.png" />
    <Content Include="Assets\Scoreboard\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\logo-boston-cut-new.ico" />
  </ItemGroup>

</Project>
